/**
 * OpenAI DALL-E 3 Service
 * High-quality image generation for general designs
 */

export interface OpenAIImageResponse {
  data: Array<{
    url: string;
    revised_prompt?: string;
  }>;
}

export interface OpenAIGenerateOptions {
  prompt: string;
  size?: '1024x1024' | '1792x1024' | '1024x1792';
  quality?: 'standard' | 'hd';
  style?: 'vivid' | 'natural';
}

export const generateImageWithOpenAI = async (options: OpenAIGenerateOptions): Promise<string> => {
  const { prompt, size = '1024x1024', quality = 'standard', style = 'vivid' } = options;
  
  const apiKey = import.meta.env.VITE_OPENAI_API_KEY;
  if (!apiKey) {
    console.warn('OpenAI API key not found. Please add VITE_OPENAI_API_KEY to your environment variables.');
    throw new Error('OpenAI API key not configured. Please run "npm run setup" to configure your API keys.');
  }

  try {
    const response = await fetch('https://api.openai.com/v1/images/generations', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'dall-e-3',
        prompt: `A high-resolution, professionally designed graphic for merchandise (t-shirt, mug). The design should be centered with a transparent or simple background. Subject: ${prompt}`,
        n: 1,
        size,
        quality,
        style,
      }),
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(`OpenAI API error: ${response.status} - ${errorData.error?.message || 'Unknown error'}`);
    }

    const data: OpenAIImageResponse = await response.json();
    
    if (!data.data || data.data.length === 0) {
      throw new Error('No image generated by OpenAI API');
    }

    return data.data[0].url;
  } catch (error) {
    console.error('OpenAI API error:', error);
    throw new Error(`Failed to generate image with OpenAI: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
};
